//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public string VolunteerName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string DOB { get; set; }
        public string Gotra { get; set; }
        public string Education { get; set; }
        public string Occupation { get; set; }
        public string MonthlyIncome { get; set; }
        public string Address { get; set; }
        public string ContactNumber { get; set; }
        public string FacebookId { get; set; }
        public string LevelofTatvavada { get; set; }
        public string Email { get; set; }
        public string CountFamilyMembers { get; set; }
        public string MedicalConditions { get; set; }
        public string Remarks { get; set; }
        public long Id { get; set; }
    }
}
